### ISSUE TITLE
Instructions for fetching analytical data that is stored as an OMERO attachment

### ISSUE THREAD

**Issue by shntnu** [idr-contrib/community#1]
Can you please provide instructions for fetching analytical data that is stored as an OMERO attachment? 

Perhaps extract the relevant parts of 
https://github.com/IDR/idr-notebooks/blob/master/notebooks/PCAanalysisOfCharmFeatures.ipynb
(specifically,`getBulkAnnotationAsDf`)

and then provide instructions for running the notebook using https://github.com/IDR/jupyter-docker

**Comment by bramalingam** [comment]
Thank you for sharing your question here.
Yes that is the right notebook and method. The same method has been used in multiple notebooks in the idr-notebooks repository. 

Although, you can get more documentation on accessing attachments or tables (based on how the analytical data is organised in OMERO) in our python documentation page,
https://docs.openmicroscopy.org/omero/5.4.2/developers/Python.html

Similar examples are available in other languages as well in our documentation pages, including Java, Matlab and R.

Reg: https://github.com/IDR/jupyter-docker
Running the docker image from the Jupyter-docker repository using the following command,
`docker build -t idr_jupyter .`

Should set up the docker image (named 'idr_jupyter') locally.
Then you can run the docker image using the commands highlighted in the readme document,
https://github.com/IDR/jupyter-docker/blob/master/README.md

The only issue you might face is that, you will not have access to the credentials for connecting with the IDR server, and currently we suggest using the production deployment of idr-jupyter from the following link to test the notebooks,
http://idr.openmicroscopy.org/jupyter/hub/home

Hope that helps.

**Comment by shntnu** [comment]
Is it possible to make the  imagedata/jupyter-docker  public? I could build it, but wondering if it is possible to pull from docker hub instead? 

This is what I get

    ~$ docker pull imagedata/jupyter-docker
    Using default tag: latest
    Error response from daemon: Get https://registry-1.docker.io/v2/imagedata/jupyter-docker/manifests/latest: unauthorized: incorrect username or password

**Comment by joshmoore** [comment]
@shntnu : all of our Docker Hub images (IDR as well as OME) are public. What version of docker is this? Can you try from another location as well?

```
[root@idr1-slot2 jamoore]# docker --version
Docker version 17.06.0-ce, build 02c1d87
[root@idr1-slot2 jamoore]# docker info | grep -i registry
Registry: https://index.docker.io/v1/
```

**Comment by shntnu** [comment]
Thanks, @joshmoore. I had flubbed. I am able to get the docker instance running now using this command

    docker run --rm -p 8888:8888 -e IDR_HOST=localhost -e IDR_USER=user -e IDR_PASSWORD=password imagedata/jupyter-docker

I was able to connect to the Jupyter Notebook at http://localhost:8888 and view notebooks

I  tried running 

notebooks/PCAanalysisOfCharmFeatures.ipynb

But it fails at 
    conn = connection()

with this error:

    SocketExceptionTraceback (most recent call last)
    <ipython-input-9-8a890fc487d3> in <module>()
    ----> 1 conn = connection()
    
    /opt/conda/envs/python2/lib/python2.7/site-packages/idr/connections.pyc in connection(host, user, password, port)
         61     c = omero.client(host, int(port))
         62     c.enableKeepAlive(300)
    ---> 63     c.createSession(user, password)
         64     conn = BlitzGateway(client_obj=c)
         65 
    
    /opt/omero/OMERO.server/lib/python/omero/clients.py in createSession(self, username, password)
        567                         ctx[omero.constants.IP] = self.__ip
        568                     rtr = self.getRouter(self.__ic)
    --> 569                     prx = rtr.createSession(username, password, ctx)
        570 
        571                     # Create the adapter
    
    /opt/conda/envs/python2/lib/python2.7/site-packages/Glacier2_Router_ice.pyc in createSession(self, userId, password, _ctx)
        256         """
        257         def createSession(self, userId, password, _ctx=None):
    --> 258             return _M_Glacier2.Router._op_createSession.invoke(self, ((userId, password), _ctx))
        259 
        260         """
    
    SocketException: Ice.SocketException:
    Cannot assign requested address    


Any thoughts?

**Comment by joshmoore** [comment]
Hi @shntnu. What's happening is that this container typically runs within the IDR network, which is the only place that the server is accessible. Unless you're running an OMERO on `localhost` (within the docker), you don't have a valid connection.

**Comment by shntnu** [comment]
@joshmoore 
Got it. 
But in that case, how do I run `dfAnn = getBulkAnnotationAsDf(scId,conn)` ? Because that's how I can access the annotations, correct?

**Comment by joshmoore** [comment]
Hi @shntnu 

At the moment, only within the IDR's VAE (i.e. jupyter). That file is nearly 1 TB:

![screen shot 2018-01-26 at 17 15 22](https://user-images.githubusercontent.com/88113/35453304-fab4f5f4-02c9-11e8-93fa-14060cce9afc.png)

You're likely best off adapting that method to use the API within jupyter to generate a smaller representation of what you're looking for.

Downloading a partial representation is something you would be able to do remotely by using the API, but we haven't yet opened the IDR servers for external access.

We're discussing the best way to do this for the upcoming (approx. 2 weeks) release of prod45. We'll keep you posted.

Cheers,
~Josh

**Comment by shntnu** [comment]
Hi @joshmoore I'm less worried about the size, because we can modify `getBulkAnnotationAsDf` appropriately.

But I assume the issue here is that you haven't opened  IDR servers for external access, so there's no way of creating the connection, correct?

i.e. currently, there's no way for me to run `conn = connection()` and be able to get the attachments regardless of size?

**Comment by joshmoore** [comment]
> But I assume the issue here is that you haven't opened IDR servers for external access, so there's no way of creating the connection, correct?  i.e. currently, there's no way for me to run conn = connection() and be able to get the attachments regardless of size?

Correct. Outside of https://idr.openmicroscopy.org/jupyter there's currently no way to access the OMERO API. For smaller attachments, however, the files are downloadable via HTTP.

**Comment by shntnu** [comment]
Got it - thanks for clarifying.

**Comment by manics** [comment]
I've emailed you details of our beta access.
