### ISSUE TITLE
CellMorph replicates

### ISSUE THREAD

**Issue by beatrizserrano** [idr-contrib/community#12]
Hi,

I'm analysing the metadata from CellMorph (idr0012). The paper mentions 3 replicates, but I can't find plates with the same layout in the metadata, so I was wondering whether only one of the replicates is available in the IDR.

Thanks!

**Comment by sbesson** [comment]
Hi @beatrizserrano, a couple of clarifications of the IDR representation of the Cellmorph dataset:

- the full [CellMorph data](http://www.huber.embl.de/cellmorph/data.php) includes two screens as described in the publication:
  - a primary screen consisting of plates HT01 to HT68 available at http://www.huber.embl.de/cellmorph/source/
  - a secondary screen performed on 604 candidates on two cell lines available at http://www.huber.embl.de/cellmorph/source-HR and http://www.huber.embl.de/cellmorph/source-UR

In terms of semantics, `idr0012/screenA` refers to the primary screen while `idr0012/screenB` and `idr0012/screenC` are the two cell lines constituting the secondary screen.

For feasibility reasons, the secondary screen work has been tabled and only `idr0012/screenA` i.e. the primary screen has been imported, annotated and published in IDR. 

Coming back to your question, are you referring to the various mentions of `three biological replicates` to construct the error bars in the paper? I could not easily find whether this data had been pulled from a combination of both the primary and secondary screen and it might be something checking with the authors.

**Comment by beatrizserrano** [comment]
Thanks @sbesson. Yes, we need to identify the biological replicates. We'll ask the authors then 😃

**Comment by sbesson** [comment]
Closing this as external input is required to re-annotate.
