### ISSUE TITLE
How to get the image data and image annotation?

### ISSUE THREAD

**Issue by Running-z** [idr-contrib/community#14]
Hello, I am implementing your API code from your API page and getting only some JSON data, but shouldn't it be image data? If I want to use deep learning and train a classification model through your data, how can I use it? I don't get any image data and annotations. Is there a good tutorial or guidance?

**Comment by sbesson** [comment]
Hi @Running-z, could we leave you to update your issue title and description with the translated content before we answer?

**Comment by Running-z** [comment]
@sbesson 
sorry, My mistake

**Comment by Running-z** [comment]
@sbesson 
I have corrected it, sorry.

**Comment by Running-z** [comment]
@sbesson 
Can I answer my question now?

**Comment by manics** [comment]
It looks like this is a duplicate, I've replied [on your other post](https://github.com/IDR/idr-notebooks/issues/67#issuecomment-404775879)
