### ISSUE TITLE
Distorted display of non-squared images with EBImage

### ISSUE THREAD

**Issue by beatrizserrano** [idr-contrib/community#16]
Hi,

I'm playing with the Jupyter notebook ``Yeast_cell_growth.ipynb``. When I replace the image by a non-squared one (e.g. imageId=``273169``) the resulting image seems to be distorted (see screenshot attached). I'm only getting that when the image width and height are not equal. Am I missing any parameter when the images are not squared?

Thanks!

<img width="774" alt="example" src="https://user-images.githubusercontent.com/11300231/57184021-65f1eb80-6eb5-11e9-96b3-f5bda6fb63bd.png">

**Comment by dominikl** [comment]
Thanks for spotting this issue. It looks like the `getPixelValues` method messes something up for non-square images. I'm not sure yet, if it is the R gateway method or the underlying Java gateway method. I'll do some more investigation and hope being able to fix the issue soon.

**Comment by beatrizserrano** [comment]
Thanks, @dominikl, I'm wondering now if that could be also affecting the Python function ``getPrimaryPixels`` that I've used already to analyse a lot of images.

I guess that the Java gateway is also underlying the Python one, right?

**Comment by dominikl** [comment]
It was actually a bug in the R gateway method, just pushed a commit fixing it: https://github.com/ome/rOMERO-gateway/pull/66 . Java and Python method are ok.

**Comment by beatrizserrano** [comment]
Perfect, thanks!

**Comment by beatrizserrano** [comment]
I see that the bug was fixed and merged to master, but I’m still having the issue. Is the version in the Jupyter notebooks updated?

**Comment by jburel** [comment]
We have not yet updated the docker image

**Comment by jburel** [comment]
https://github.com/IDR/idr-notebooks/pull/92 upgrade version in dockerfile
We will then need to deploy the new image to make it available via itr

**Comment by jburel** [comment]
Fixed in https://github.com/IDR/idr-notebooks/releases/tag/ITR-0.1.0
