### ISSUE TITLE
Some functions missing in rOMERO.gateway

### ISSUE THREAD

**Issue by beatrizserrano** [idr-contrib/community#17]
I’m trying to use some functions from the rOMERO-gateway package. For instance, ```addROIs``` is in this [example](https://github.com/ome/rOMERO-gateway/blob/master/examples/ROIs.R). However, when I use them in my Jupyter notebook I get the error _"could not find function addROIs"_. If I list the available functions of the package in the notebook with ```lsf.str(“package:romero.gateway”)``` I get a shorter list than in the [documentation](https://rdrr.io/cran/romero.gateway/man/). Any hints? Are there maybe different versions of the package?

Thanks!

Beatriz

**Comment by dominikl** [comment]
I think that's probably the same issue as https://github.com/idr-contrib/community/issues/16#issuecomment-504362132 . I see if I can get the latest version of the R gateway into the docker image.

**Comment by jburel** [comment]
included in https://github.com/IDR/idr-notebooks/releases/tag/ITR-0.1.0
