### ISSUE TITLE
Uneven channel order in screen idr0006

### ISSUE THREAD

**Issue by beatrizserrano** [idr-contrib/community#18]
I've found uneven channel order in the dataset ```idr0006``` (a couple of examples [here](http://idr.openmicroscopy.org/webclient/img_detail/352577/) and [here](http://idr.openmicroscopy.org/webclient/img_detail/971812/)). 

In particular, I'm interested in the DAPI channel, so when I access through the Python API, the parameter ```theC``` in the function ```getTile()``` takes different values (0,1) for the examples above. Is there an unambiguous way to select the DAPI channel?

Thanks!

Beatriz

**Comment by jburel** [comment]
You will first need to check the name associated to the channel to determine its index.
The method  ``image.getChannelLabels`` should return the name of the channels i.e. one entry per channel. If the name is ``DAPI`` then you will know which index to specify to ``getTile``

**Comment by sbesson** [comment]
Closing as per https://github.com/idr-contrib/community/issues/18#issuecomment-505068157

**Comment by sbesson** [comment]
Closing as per https://github.com/idr-contrib/community/issues/18#issuecomment-505068157
