### ISSUE TITLE
Several annotation files in idr0043

### ISSUE THREAD

**Issue by beatrizserrano** [idr-contrib/community#19]
I see 5 runs in the annotation files in the dataset ```idr0043```. I've checked that each one contains a different set of folder ids (e.g. ```CAB046445```) but also a variable number of columns. The latter makes me wonder whether the separation in these 5 files is just a splitting or there are some experimental conditions/extra metadata that I'm missing.

Thanks a lot,

Beatriz

**Comment by dominikl** [comment]
Yes, each run contains the images for 1000 antibodies. What is different in the annotation files is the number of `Comment [Gene Identifier]` and `Comment [Gene Symbol]` columns. This depends on the maximum number of gene annotations in each run, e. g. if there is an image in a run which is annotated with 5 genes, there will be at least 5 `Comment [Gene Identifier]` and 5 `Comment [Gene Symbol]` columns.

**Comment by beatrizserrano** [comment]
Thanks @dominikl! that's what I suspected but wanted to have a confirmation :)
