### ISSUE TITLE
Pulling data from the IDR

### ISSUE THREAD

**Issue by dnmason** [idr-contrib/community#2]
The ImageJ plugin support is really helpful for pulling (and pushing) data to an OMERO server. 

As one method to enhance data reuse / reanalysis, it would be useful to be able to connect to the IDR and pull data (into memory/disk) as part of a batch processing pipeline in ImageJ/Fiji. 

Furthermore, a solution may be applicable to any public-accessible data on an institutionally hosted OMERO server (eg. https://omero.lifesci.dundee.ac.uk/pub/schleicher-et-al-2017 ) which at present I don't think allows for download / analysis of data (without an account on the server), although this is perhaps a discussion for the 2018 users' meeting.

**Comment by joshmoore** [comment]
Hi @dnmason We're looking into making public login to the IDR accessible for more than just the web client. Stay tuned!

**Comment by manics** [comment]
I've emailed you details of our beta access.
