### ISSUE TITLE
ilastik with IDR data

### ISSUE THREAD

**Issue by beatrizserrano** [idr-contrib/community#20]
Hi,

I was wondering if one could run non-interactive analysis on _ilastik_ with image objects from the IDR.

Thanks,

Beatriz

**Comment by joshmoore** [comment]
Hi @beatrizserrano,

Thanks for raising this. At the moment, it's a work-in-progress and we're not sure when we'd have, e.g., a notebook available in https://idr-analysis.openmicroscopy.org/. We'll start ramping back up on that after the current batch of summer vacations. If anyone else has examples they'd like to share in the meantime, feel free.

~Josh

cc: @jburel

**Comment by jburel** [comment]
We have added example on how to connect OMERO/idr and ilastik
https://omero-guides.readthedocs.io/en/latest/ilastik/docs/ilastik.html
