### ISSUE TITLE
mount point for idr images?

### ISSUE THREAD

**Issue by sunyi000** [idr-contrib/community#25]
I'm just curious to know where are all the raw images stored in idr. 

If it is on a server within embassy cloud, would it be possible to provide a public read-only mount point? 

Is the server which stores all the images within idr's own project, or somewhere in the embassy cloud's central storage server?

we have a tenant in embassy cloud too,  using api to download images are not very optimal. If there's a nfs mount point available, it will saves us lots of time downloading the images.

Thanks very much
Yi

**Comment by manics** [comment]
Hi Yi

The internal EBI mount-point has restricted filesystem permissions, so you won't be able to access most of the data.

Are you able to give us more information on how you want to use the images? We have a public OMERO API for querying and extracting metadata and image pixel data that might be more suitable.

**Comment by sunyi000** [comment]
Thanks Simon, we already use the API to access images in idr. 

we need to download approx. 200,000+ images, and that takes ages to download all.

we tried to download 12645 images, it took 1,5 hrs... so am just thinking if there's other options could speed things up.

I don't know much about the images themselves, so I will have to talk to someone and then discuss further.

thanks

**Comment by manics** [comment]
One of the aims of the IDR is to support online analysis so any feedback you can give is valuable.

If you do need to download the raw data you can use aspera: https://idr.openmicroscopy.org/about/download.html

**Comment by sbesson** [comment]
Closing as per https://github.com/idr-contrib/community/issues/25#issuecomment-581873639 i.e. at the moment there is no direct access to NFS and Aspera is the recommended way to download raw data. We are currently investigating new endpoints for accessing the binary data and should be able to update more at the upcoming [OME Community meeting](https://www.openmicroscopy.org/events/ome-community-meeting-2020/)
