### ISSUE TITLE
Download several images as a single file

### ISSUE THREAD

**Issue by beatrizserrano** [idr-contrib/community#28]
Hi,

We are assembling our workflow in Galaxy using the [IDR download tool](https://github.com/galaxyproject/tools-iuc/tree/master/tools/idr_download) and then the CellProfiler tools that @sunyi000 has been wrapping. Since we are downloading a large number of images and we select just one cropped channel, we end up with a large collection of small files, meaning lots of I/O operations. We are thinking about improving the performance with 2 different options:
- Having a multi-page TIFF downloaded from the IDR that would be the input of CellProfiler. For instance, one multi-page TIFF could contain all the TIFF images that we need from the same plate for a particular channel. In this case, we need CellProfiler to be able to read that multi-page TIFF too. I've posted the [question in image.sc](https://forum.image.sc/t/alternative-ways-of-handling-a-huge-number-of-images-as-input-for-cellprofiler/36842).

- Having a zip/tar file downloaded from the IDR and uncompressing that in the CellProfiler tool (see PR [here](https://github.com/bgruening/galaxytools/pull/989)). Could we get such a compressed file directly from the IDR? 

Any other options that you can think of to improve the performance? 

Thanks a lot for your inputs!

Beatriz

**Comment by jkh1** [comment]
I would think that a zip/tar archive would be the most generic solution. As pointed out, at the moment, it's unclear whether we can make use of a multipage TIFF containing unrelated images (the software assumption seems to be that a multipage TIFF contains images of the same field of view either as volume slices, time series or different channels).

**Comment by manics** [comment]
It looks like you found a solution in your image.sc post: https://forum.image.sc/t/alternative-ways-of-handling-a-huge-number-of-images-as-input-for-cellprofiler/36842/2

As a long term solution we'll eventually make everything available in the new Zarr format on cloud object storage: https://forum.image.sc/t/publication-of-idr0083-sars-cov-2-up-close-in-a-human-organoid/37163
