### ISSUE TITLE
Error instantiating pixel buffer

### ISSUE THREAD

**Issue by beatrizserrano** [idr-contrib/community#5]
Hi,

I'm downloading the images from idr0009-simpson-secretion/screenA (id 251), specifically the plate 0002-12--2005-09-08 (id 2956).
When I try to access the image with id 1345039 (position P24 in the grid), I've got the following error:

Error instantiating pixel buffer: /data/OMERO/ManagedRepository/demo_2/2015-12/08/09-05-47.246/experiment_descriptor.xml

Thanks!

**Comment by joshmoore** [comment]
I'm seeing the same behavior:

```

ResourceErrorTraceback (most recent call last)
<ipython-input-8-a286779c9ccf> in <module>()
----> 1 rps.setPixelsId(1345039, False)

/opt/conda/envs/python2/lib/python2.7/site-packages/omero_api_RawPixelsStore_ice.pyc in setPixelsId(self, pixelsId, bypassOriginalFile, _ctx)
    515         """
    516         def setPixelsId(self, pixelsId, bypassOriginalFile, _ctx=None):
--> 517             return _M_omero.api.RawPixelsStore._op_setPixelsId.invoke(self, ((pixelsId, bypassOriginalFile), _ctx))
    518 
    519         """

ResourceError: exception ::omero::ResourceError
{
    serverStackTrace = ome.conditions.ResourceError: Error instantiating pixel buffer: /data/OMERO/ManagedRepository/demo_2/2015-12/08/09-05-47.246/experiment_descriptor.xml
	at ome.io.nio.PixelsService.createBfPixelBuffer(PixelsService.java:817)
	at ome.io.nio.PixelsService._getPixelBuffer(PixelsService.java:578)
	at ome.io.nio.PixelsService.getPixelBuffer(PixelsService.java:496)
	at ome.services.RawPixelsBean.setPixelsId(RawPixelsBean.java:284)
	at sun.reflect.GeneratedMethodAccessor1101.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflec
```

We'll take a look at what's going on. Thanks for the heads up.

**Comment by sbesson** [comment]
@beatrizserrano thanks for raising this to our attention.  Our suspicion is some of the custom fixes brought to Bio-Formats to handle the images of this study were lost during the upgrade of IDR from OMERO 5.2 to OMERO 5.3. We are investigating how easy it is to restore these changes (see [card](https://trello.com/c/p7Yw5UYu/3-idr0009-issues)) and hope to have this issue fixed in an upcoming release of IDR.

**Comment by sbesson** [comment]
Coming back to this, the fix has been deployed so that https://idr.openmicroscopy.org/webclient/img_detail/1345039/ is now resolving. Closing this as fixed. Thanks for reporting.
