### ISSUE TITLE
Install OMERO library

### ISSUE THREAD

**Issue by beatrizserrano** [idr-contrib/community#7]
Hi,

In order to access the Python API, I'm installing this OMERO library:

http://downloads.openmicroscopy.org/omero/5.3.5/artifacts/OMERO.py-5.3.5-ice36-b73.zip

But I get an error when installing Ice3.6 in this way:
```
cd /etc/yum.repos.d
sudo wget https://zeroc.com/download/rpm/zeroc-ice-el6.repo
sudo yum -y install gcc-c++
sudo yum -y install libdb-utils
sudo yum -y install openssl-devel bzip2-devel expat-devel
sudo yum -y install ice-all-runtime ice-all-devel
pip install "zeroc-ice>3.5,<3.7"
```
The last command (```pip install "zeroc-ice>3.5,<3.7"```) yields:

	Command "/usr/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-IuF1Tw/zeroc-ice/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-KRXNGF-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-IuF1Tw/zeroc-ice/

Any help? Would it be easier to use the Docker container (https://hub.docker.com/r/imagedata/jupyter-docker/)? Would this container allow scalability or is just for Jupyter notebooks?

Thanks in advance!

**Comment by manics** [comment]
You can use that docker image. Alternatively if you've got Anaconda (Python 2.7) available you can use conda to manage everything: https://github.com/IDR/idr-py/pull/11/files#diff-081467603ca51a4d96b80584e3689b5f

**Comment by beatrizserrano** [comment]
Thanks! Using Anaconda it has worked, also the wnd-charm API. Starting to compute features soon :D
