### ISSUE TITLE
Getting inf and nan in some features

### ISSUE THREAD

**Issue by beatrizserrano** [idr-contrib/community#9]
For some images, the resulting features after applying wnd-charm are weird. For instance, when analysing the blue channel of image 171247 (http://idr.openmicroscopy.org/webclient/img_detail/171247/) I get `nan` values for Zernike and Comb moments, `inf` for Tamura. The remaining two channels are ok. 

Also, for image 171496 (http://idr.openmicroscopy.org/webclient/img_detail/171496/), which is empty, `nan` values show up for all 3 channels.

My suspicion was that these could be happening due to the artifacts, so I tried 567601 that is also defective  (http://idr.openmicroscopy.org/webclient/img_detail/567601/) but I got descriptive features for all channels, i.e., no `nans` or `infs` there.

Any ideas of the reason?

**Comment by joshmoore** [comment]
Hi @beatrizserrano. Can you share the code you're using?

**Comment by beatrizserrano** [comment]
Sure. Here you have it:

```
image = conn.getObject("Image", imageID)
imageROI = image.getPrimaryPixels().getTile(theC=channel, theT=timepoint, tile=cropParams)

from wndcharm.PyImageMatrix import PyImageMatrix
matrix = PyImageMatrix()
matrix.allocate(imageROI.shape[1], imageROI.shape[0])
numpy_matrix = matrix.as_ndarray()
numpy_matrix[:] = imageROI[:, :]

from wndcharm.FeatureVector import FeatureVector
fv = FeatureVector(name=featureFilename, long=True, original_px_plane=matrix)
fv.GenerateFeatures(quiet=False, write_to_disk=True)
```

**Comment by manics** [comment]
I can reproduce what you've found with `cropParams = (336, 256, 672, 512)`. My guess is it's related to the variation in pixel intensities in the selected tile in those images- with very low or zero variation there's probably a scaling error in the feature calculation. If you want to dig further try asking on https://github.com/wnd-charm/wnd-charm/issues

**Comment by beatrizserrano** [comment]
Thanks @manics. Yes, these are exactly the parameters I've used. It’s probably what you mentioned but I’ve asked [here](https://github.com/wnd-charm/wnd-charm/issues/118).
